# Generated by Django 4.1.7 on 2023-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Заявки'),
        ),
    ]
