# Generated by Django 4.1.7 on 2023-03-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_application_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Requests',
        ),
    ]
